# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Rockyfor3DInputRasters
                                 A QGIS plugin
 This plugin prepares the input rasters for Rockyfor3D.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-24
        copyright            : (C) 2025 by ecorisQ
        email                : a.erbach@posteo.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'ecorisQ'
__date__ = '2025-04-24'
__copyright__ = '(C) 2025 by ecorisQ'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Rockyfor3DInputRasters class from file Rockyfor3DInputRasters.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rockyfor3d_inputs import Rockyfor3DInputRastersPlugin
    return Rockyfor3DInputRastersPlugin(iface)
